services:
  # 1. Keycloak Database
  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak -d keycloak" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # 2. Identity Provider (Keycloak)
  keycloak:
    image: quay.io/keycloak/keycloak:26.7.0
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true
    restart: unless-stopped
    depends_on:
      keycloak-db:
        condition: service_healthy

  # 3. Ledger Service Database
  ledger-db:
    image: postgres:15
    container_name: ledger-db
    environment:
      POSTGRES_DB: ledger
      POSTGRES_USER: ledger_user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432" # Mapped to 5433 to avoid port conflict with Keycloak DB
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ledger_user -d ledger" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # 4. Redis (Caching & Rate Limiting)
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  # 5. RabbitMQ (Event Broker)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # Management UI port
    restart: unless-stopped
