const fs = require('fs');

const dtsPath = 'node_modules/.prisma/client/index.d.ts';
const jsPath = 'node_modules/.prisma/client/index.js';

const enums = `
export enum KycStatus { PENDING = 'PENDING', SUBMITTED = 'SUBMITTED', VERIFIED = 'VERIFIED', REJECTED = 'REJECTED' }
export enum UserStatus { ACTIVE = 'ACTIVE', SUSPENDED = 'SUSPENDED', DEACTIVATED = 'DEACTIVATED' }
export enum AccountType { SAVINGS = 'SAVINGS', CURRENT = 'CURRENT', FIXED_DEPOSIT = 'FIXED_DEPOSIT', LOAN = 'LOAN' }
export enum AccountStatus { ACTIVE = 'ACTIVE', FROZEN = 'FROZEN', DORMANT = 'DORMANT', CLOSED = 'CLOSED' }
export enum LoanStatus { PENDING = 'PENDING', REVIEWING = 'REVIEWING', APPROVED = 'APPROVED', REJECTED = 'REJECTED', ACTIVE = 'ACTIVE', CLOSED = 'CLOSED' }
export enum ApprovalStatus { PENDING = 'PENDING', APPROVED = 'APPROVED', REJECTED = 'REJECTED' }
export enum TransactionType { DEPOSIT = 'DEPOSIT', WITHDRAWAL = 'WITHDRAWAL', TRANSFER = 'TRANSFER', FEE = 'FEE', INTEREST = 'INTEREST', REVERSAL = 'REVERSAL' }
export enum TransactionStatus { PENDING = 'PENDING', PROCESSING = 'PROCESSING', COMPLETED = 'COMPLETED', FAILED = 'FAILED', REVERSED = 'REVERSED' }
export enum EntryType { DEBIT = 'DEBIT', CREDIT = 'CREDIT' }
export enum NotificationChannel { EMAIL = 'EMAIL', SMS = 'SMS', PUSH = 'PUSH' }
export enum NotificationStatus { PENDING = 'PENDING', SENT = 'SENT', DELIVERED = 'DELIVERED', FAILED = 'FAILED' }
export enum OutboxStatus { PENDING = 'PENDING', PROCESSING = 'PROCESSING', PROCESSED = 'PROCESSED', FAILED = 'FAILED', DEAD_LETTER = 'DEAD_LETTER' }
export enum SagaStatus { STARTED = 'STARTED', RUNNING = 'RUNNING', COMPLETED = 'COMPLETED', COMPENSATING = 'COMPENSATING', COMPENSATED = 'COMPENSATED', FAILED = 'FAILED' }
export enum SagaStepStatus { PENDING = 'PENDING', RUNNING = 'RUNNING', COMPLETED = 'COMPLETED', COMPENSATING = 'COMPENSATING', COMPENSATED = 'COMPENSATED', FAILED = 'FAILED' }
`;

const jsEnums = `
exports.KycStatus = { PENDING: 'PENDING', SUBMITTED: 'SUBMITTED', VERIFIED: 'VERIFIED', REJECTED: 'REJECTED' };
exports.UserStatus = { ACTIVE: 'ACTIVE', SUSPENDED: 'SUSPENDED', DEACTIVATED: 'DEACTIVATED' };
exports.AccountType = { SAVINGS: 'SAVINGS', CURRENT: 'CURRENT', FIXED_DEPOSIT: 'FIXED_DEPOSIT', LOAN: 'LOAN' };
exports.AccountStatus = { ACTIVE: 'ACTIVE', FROZEN: 'FROZEN', DORMANT: 'DORMANT', CLOSED: 'CLOSED' };
exports.LoanStatus = { PENDING: 'PENDING', REVIEWING: 'REVIEWING', APPROVED: 'APPROVED', REJECTED: 'REJECTED', ACTIVE: 'ACTIVE', CLOSED: 'CLOSED' };
exports.ApprovalStatus = { PENDING: 'PENDING', APPROVED: 'APPROVED', REJECTED: 'REJECTED' };
exports.TransactionType = { DEPOSIT: 'DEPOSIT', WITHDRAWAL: 'WITHDRAWAL', TRANSFER: 'TRANSFER', FEE: 'FEE', INTEREST: 'INTEREST', REVERSAL: 'REVERSAL' };
exports.TransactionStatus = { PENDING: 'PENDING', PROCESSING: 'PROCESSING', COMPLETED: 'COMPLETED', FAILED: 'FAILED', REVERSED: 'REVERSED' };
exports.EntryType = { DEBIT: 'DEBIT', CREDIT: 'CREDIT' };
exports.NotificationChannel = { EMAIL: 'EMAIL', SMS: 'SMS', PUSH: 'PUSH' };
exports.NotificationStatus = { PENDING: 'PENDING', SENT: 'SENT', DELIVERED: 'DELIVERED', FAILED: 'FAILED' };
exports.OutboxStatus = { PENDING: 'PENDING', PROCESSING: 'PROCESSING', PROCESSED: 'PROCESSED', FAILED: 'FAILED', DEAD_LETTER: 'DEAD_LETTER' };
exports.SagaStatus = { STARTED: 'STARTED', RUNNING: 'RUNNING', COMPLETED: 'COMPLETED', COMPENSATING: 'COMPENSATING', COMPENSATED: 'COMPENSATED', FAILED: 'FAILED' };
exports.SagaStepStatus = { PENDING: 'PENDING', RUNNING: 'RUNNING', COMPLETED: 'COMPLETED', COMPENSATING: 'COMPENSATING', COMPENSATED: 'COMPENSATED', FAILED: 'FAILED' };
`;

fs.appendFileSync(dtsPath, '\\n' + enums);
fs.appendFileSync(jsPath, '\\n' + jsEnums);
console.log('Enums injected into Prisma client!');
